apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager-client
  template:
    metadata:
      labels:
        app: taskmanager-client
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2223"
    spec:
      containers:
      - name: client
        image: maciekb2/task-manager-client:latest
        ports:
        - containerPort: 2223
