apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: .*
      - job_name: 'promtail'
        static_configs:
          - targets: ['promtail.default.svc.cluster.local:9080']
      - job_name: 'loki'
        static_configs:
          - targets: ['loki.default.svc.cluster.local:3100']
      - job_name: 'redis-exporter'
        static_configs:
        - targets:
          - 'redis-exporter.default.svc.cluster.local:9121'

    remote_write:
      - url: "http://mimir.default.svc.cluster.local:9090/api/v1/push"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/
          ports:
            - containerPort: 9090
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: prometheus
