apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager-server
  template:
    metadata:
      labels:
        app: taskmanager-server
    spec:
      containers:
      - name: server
        image: maciekb2/task-manager-server:latest
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
spec:
  type: ClusterIP
  selector:
    app: taskmanager-server
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
