// Package proto defines the gRPC service and message definitions
// for the Task Manager application.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/taskmanager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskPriority represents the priority level of a task.
type TaskPriority int32

const (
	// LOW indicates a low priority task.
	TaskPriority_LOW TaskPriority = 0
	// MEDIUM indicates a medium priority task.
	TaskPriority_MEDIUM TaskPriority = 1
	// HIGH indicates a high priority task.
	TaskPriority_HIGH TaskPriority = 2
)

// Enum value maps for TaskPriority.
var (
	TaskPriority_name = map[int32]string{
		0: "LOW",
		1: "MEDIUM",
		2: "HIGH",
	}
	TaskPriority_value = map[string]int32{
		"LOW":    0,
		"MEDIUM": 1,
		"HIGH":   2,
	}
)

func (x TaskPriority) Enum() *TaskPriority {
	p := new(TaskPriority)
	*p = x
	return p
}

func (x TaskPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_taskmanager_proto_enumTypes[0].Descriptor()
}

func (TaskPriority) Type() protoreflect.EnumType {
	return &file_proto_taskmanager_proto_enumTypes[0]
}

func (x TaskPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskPriority.Descriptor instead.
func (TaskPriority) EnumDescriptor() ([]byte, []int) {
	return file_proto_taskmanager_proto_rawDescGZIP(), []int{0}
}

// TaskRequest represents a request to submit a new task.
type TaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_description is a brief description of the task.
	TaskDescription string `protobuf:"bytes,1,opt,name=task_description,json=taskDescription,proto3" json:"task_description,omitempty"`
	// priority indicates the priority level of the task.
	Priority TaskPriority `protobuf:"varint,2,opt,name=priority,proto3,enum=proto.TaskPriority" json:"priority,omitempty"`
	// url is the target URL to check.
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// method is the HTTP method to use (GET, POST, etc.).
	Method string `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	// idempotency_key provides a stable key for de-duplication.
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_taskmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskmanager_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetTaskDescription() string {
	if x != nil {
		return x.TaskDescription
	}
	return ""
}

func (x *TaskRequest) GetPriority() TaskPriority {
	if x != nil {
		return x.Priority
	}
	return TaskPriority_LOW
}

func (x *TaskRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TaskRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *TaskRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// TaskResponse represents a response after submitting a task.
type TaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the unique identifier of the submitted task.
	TaskId        string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_taskmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskmanager_proto_rawDescGZIP(), []int{1}
}

func (x *TaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// StatusRequest represents a request to get the status of a task.
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// task_id is the unique identifier of the task whose status is being requested.
	TaskId        string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_taskmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_taskmanager_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

// StatusResponse represents the status of a task.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status is the current status of the task.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_taskmanager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_taskmanager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_taskmanager_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_taskmanager_proto protoreflect.FileDescriptor

const file_proto_taskmanager_proto_rawDesc = "" +
	"\n" +
	"\x17proto/taskmanager.proto\x12\x05proto\"\xbc\x01\n" +
	"\vTaskRequest\x12)\n" +
	"\x10task_description\x18\x01 \x01(\tR\x0ftaskDescription\x12/\n" +
	"\bpriority\x18\x02 \x01(\x0e2\x13.proto.TaskPriorityR\bpriority\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"'\n" +
	"\fTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status*-\n" +
	"\fTaskPriority\x12\a\n" +
	"\x03LOW\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x022\x87\x01\n" +
	"\vTaskManager\x125\n" +
	"\n" +
	"SubmitTask\x12\x12.proto.TaskRequest\x1a\x13.proto.TaskResponse\x12A\n" +
	"\x10StreamTaskStatus\x12\x14.proto.StatusRequest\x1a\x15.proto.StatusResponse0\x01B(Z&github.com/maciekb2/task-manager/protob\x06proto3"

var (
	file_proto_taskmanager_proto_rawDescOnce sync.Once
	file_proto_taskmanager_proto_rawDescData []byte
)

func file_proto_taskmanager_proto_rawDescGZIP() []byte {
	file_proto_taskmanager_proto_rawDescOnce.Do(func() {
		file_proto_taskmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_taskmanager_proto_rawDesc), len(file_proto_taskmanager_proto_rawDesc)))
	})
	return file_proto_taskmanager_proto_rawDescData
}

var file_proto_taskmanager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_taskmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_taskmanager_proto_goTypes = []any{
	(TaskPriority)(0),      // 0: proto.TaskPriority
	(*TaskRequest)(nil),    // 1: proto.TaskRequest
	(*TaskResponse)(nil),   // 2: proto.TaskResponse
	(*StatusRequest)(nil),  // 3: proto.StatusRequest
	(*StatusResponse)(nil), // 4: proto.StatusResponse
}
var file_proto_taskmanager_proto_depIdxs = []int32{
	0, // 0: proto.TaskRequest.priority:type_name -> proto.TaskPriority
	1, // 1: proto.TaskManager.SubmitTask:input_type -> proto.TaskRequest
	3, // 2: proto.TaskManager.StreamTaskStatus:input_type -> proto.StatusRequest
	2, // 3: proto.TaskManager.SubmitTask:output_type -> proto.TaskResponse
	4, // 4: proto.TaskManager.StreamTaskStatus:output_type -> proto.StatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_taskmanager_proto_init() }
func file_proto_taskmanager_proto_init() {
	if File_proto_taskmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_taskmanager_proto_rawDesc), len(file_proto_taskmanager_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_taskmanager_proto_goTypes,
		DependencyIndexes: file_proto_taskmanager_proto_depIdxs,
		EnumInfos:         file_proto_taskmanager_proto_enumTypes,
		MessageInfos:      file_proto_taskmanager_proto_msgTypes,
	}.Build()
	File_proto_taskmanager_proto = out.File
	file_proto_taskmanager_proto_goTypes = nil
	file_proto_taskmanager_proto_depIdxs = nil
}
